#! /bin/sh

sxhkd &
refreshpolybar &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

#### BSPWM configuration ####
#bspc config border_radius 8
bspc config border_width                  2
bspc config window_gap                    20
bspc config top_padding                   70
bspc config bottom_padding                10
bspc config left_padding                  10
bspc config right_padding                 10
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.70
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#### BSPWM coloring ####
bspc config normal_border_color           "#000000"
bspc config active_border_color           "#1e1e1e"
bspc config focused_border_color          "#eeeeee"
bspc config presel_feedback_color         "#5e81ac"
bspc config urgent_border_color           "#dd2727"


bspc rule -a Emacs state=tiled follow=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a firefox desktop='^1 follow=off'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
