;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-word
        c-electric-brace
        c-electric-semi&comma
        c-indent-line-or-region
        end-of-visual-line
        indent-for-tab-command
        kill-region
        move-line-down
        move-line-up
        org-beginning-of-line
        org-kill-line
        org-self-insert-command
        smex
        sp-remove-active-pair-overlay
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        counsel-find-file
        custom-undo
        describe-key
        eval-buffer
        evil-mode
        handle-switch-frame
        help-for-help
        keyboard-escape-quit
        org-return
        swiper
        ))
