;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-semi&comma
	c-indent-line-or-region
	indent-for-tab-command
	move-line-down
	move-line-up
	suspend-frame
	))

(setq mc/cmds-to-run-once
      '(
	counsel-find-file
	help-for-help
	swiper
	))
